name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main, jok26r-patch-2]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          cat $GITHUB_EVENT_PATH
